### ISSUE TITLE
New generateDrugUtilisationCohortSet API

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/DrugUtilisation#322]
```
cdm <- generateDrugUtilisationCohortSet(
  cdm,
  name,
  conceptSetList,
  durationRange = c(0, Inf),
  imputeDuration = FALSE,
  imputeDurationMethod = c("mode", "median", "mean"),
  gapEra = 0,
  limit = c("all", "first", "first ever"),
  priorUseWashout = 0,
  priorObservation = 0,
  cohortDateRange = as.Date(c(NA, NA))
)
```
The arguments appear in the order they are applied:
- first correction of durationRange. Options for imputeDuration are: "mode", "mean", "median", if multiple are provided the first one is used. Imputation only takes place if imputeDuration is TRUE, otherwise they are eliminated.
- second correction gapEra (no modification).
- limit can be "all", "first" or "first ever". If multiple are provided the first one is used. If limit is all, nothing is done. if limit it is first, **at the end** we filter only for the first record per person. If limit is firt ever we filter at this stage and only keep first record per individual.
- priorUseWashout (no modification).
- priorObservation (no modification).
- cohortDateRange (no modification).

@edward-burn @MimiYuchenGuo @ilovemane @KimLopezGuell 

#319 #316 #318 #317

**Comment by MimiYuchenGuo** [comment]
> Wouldn't first be first within cohort date range (and then washout infinity could be used to make sure it was the first ever in a person's history?)

@catalamarti So is this what we are doing? 
1. If limit == FirstEver and we filter this after trimming cohortDateRange, then we throw an error if priorUseWashout is provided by the user. Then set it as Inf to make sure we get the first. What about the priorObservation, is it not allowed under the FirstEver setting?
2. If limit == First, we get the first era at the end, after priorUseWashout, priorObservation and cohortDateRange? Do we still consider this option?

**Comment by catalamarti** [comment]
agreed with @MimiYuchenGuo 
```
cdm <- generateDrugUtilisationCohortSet(
  cdm,
  name,
  conceptSetList,
  durationRange = c(1, Inf),
  imputeDuration = c("none", "mode", "median", "mean"), # also a numeric
  missingEndDate = imputeDuration,
  gapEra = 0,
  priorUseWashout = 0,
  priorObservation = 0,
  cohortDateRange = as.Date(c(NA, NA)),
  limit = c("all", "first")
)
```
