### ISSUE TITLE
splitSubexposures error

### ISSUE THREAD

**Issue by MimiYuchenGuo** [darwin-eu-dev/DrugUtilisation#339]
If cohortInfo is empty, this line will lead to an error:

https://github.com/darwin-eu-dev/DrugUtilisation/blob/a6aac4d660cfb04abf104437eceb90c0fa848afd/R/addDrugUse.R#L587

Error in `collect()` at dbplyr/R/tbl-sql.R:76:2:
! Failed to collect lazy table.
Caused by error:
! Failed to prepare query: ERROR:  column "subexposure_start_date" does not exist
LINE 3: WHERE (("subexposure_start_date" IS NULL))
                ^
Run `rlang::last_trace()` to see where the error occurred.

**Comment by catalamarti** [comment]
hi @MimiYuchenGuo  can you try if still happens with the new version?

**Comment by catalamarti** [comment]
@MimiYuchenGuo
