### ISSUE TITLE
concept creation vignette has inconsistent cdm naming

### ISSUE THREAD

**Issue by martaalcalde** [darwin-eu-dev/DrugUtilisation#351]
- It is named cdm1, cdm2, ... without any reason.
- change asthma_1 -> asthma

**Comment by MimiYuchenGuo** [comment]
So when I use everything as cdm, it took ages to generate the vignette due to infinite loop problem in cdm reference in cdmconnector. Not sure if it's fixed by @catalamarti

**Comment by catalamarti** [comment]
yes, that was the memory issue, hopefully it should be solved @MimiYuchenGuo

**Comment by martaalcalde** [comment]
shall i try to change the vignette and see if there is any problem with
that now?

Missatge de catalamarti ***@***.***> del dia dv., 27 d’oct.
2023 a les 16:52:

**Comment by catalamarti** [comment]
yes

**Comment by catalamarti** [comment]
#352
