### ISSUE TITLE
SQL compilation error: Table "medications_set"' does not exist or not authorized

### ISSUE THREAD

**Issue by jasgratton** [darwin-eu-dev/DrugUtilisation#354]
Hi,

When calling cdm <- DrugUtilisation::generateDrugUtilisationCohortSet(cdm = cdm,
                                                           name = medicationsCohortTableName,
                                                           conceptSet = medicationsList)
 I get the following error:
 ERROR [2023-11-13 11:49:20] Error: nanodbc/nanodbc.cpp:1509: 00000: SQL compilation error:
Table 'PA.STUDY_REFERENCE."medications_set"' does not exist or not authorized. 

This error doesn't happen when running the package on a larger database, which makes me wonder whether the function has been configured to handle null result cases?

Thank you,

**Comment by catalamarti** [comment]
Hi I have tested it and it works with an empty cohort:

``` r
library(DrugUtilisation)
cdm <- mockDrugUtilisation()
cdm <- generateDrugUtilisationCohortSet(cdm = cdm, name = "empty", conceptSet = list("not_present_code" = c(123456789)))
cdm$empty
#> # Source:   table<empty> [0 x 4]
#> # Database: DuckDB 0.7.1 [martics@Windows 10 x64:R 4.2.1/:memory:]
#> # ℹ 4 variables: cohort_definition_id <int>, subject_id <dbl>,
#> #   cohort_start_date <date>, cohort_end_date <date>
```

<sup>Created on 2023-11-13 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

From what I can see and I guess:
"PA" is the prefix, "STUDY_REFRENCE" is the schema,

Was the connection created like this:
`writeSchema = c(schema = "STUDY_REFRENCE", prefix = "PA")` With this specific order?

Because I guess that it should try to read:
`STUDY_REFERENCE.PAmedications_set`

Or sth similar?

@ginberg @jasgratton 

Happy to follow this to see where the error comes from

**Comment by jasgratton** [comment]
Thanks @catalamarti !

Sorry "PA" is not a prefix, it's the name of the database (I just removed the country name for github).  'PA.STUDY_REFERENCE."medications_set"' should be correct.

There was an error previously for this same database where Table 'PA.STUDY_REFERENCE."infections_set"' does not exist or not authorized when calling  cdm <- DrugUtilisation::generateDrugUtilisationCohortSet(cdm = cdm,
                                                           name = infectionsCohortTableName,
                                                           conceptSet = infectionsList)

However this was fixed when replacing that with   cdm <- CDMConnector::generateConceptCohortSet(cdm = cdm,
                                                name = infectionsCohortTableName,
                                                conceptSet = infectionsList,
                                                limit = "first",
                                                end = "observation_period_end_date",
                                                overwrite = TRUE)

@ginberg please correct me if I'm wrong.

Again, generateDrugUtilisationCohortSet works on our other database so it's a bit puzzling.

**Comment by ginberg** [comment]
@jasgratton yes that's right. For the infections the error disappeared when we used generateConceptCohortSet instead of generateDrugUtilisationCohortSet.

**Comment by catalamarti** [comment]
but then it was not a cohort of drugs? @ginberg

**Comment by catalamarti** [comment]
The output of:
```
```

**Comment by ginberg** [comment]
@catalamarti sorry to confuse you but this error is not about the infections.

For the medications we should use DrugUtilisation::generateDrugUtilisationCohortSet. This is basically what we are doing in the code. I will try to make a reprex on the test snowflake account we have.

```
medicationsList <- CodelistGenerator::codesFromConceptSet(system.file("medications", package = "P2C1005DrugUtilisationGastroparesis"),
                                                           cdm = cdm)
  names(medicationsList) <- gsub(" ", "_", tolower(names(medicationsList)))
  medicationsCohortTableName <- "medications"
  cdm <- DrugUtilisation::generateDrugUtilisationCohortSet(cdm = cdm,
                                                           name = medicationsCohortTableName,
                                                           conceptSet = medicationsList)
```

**Comment by catalamarti** [comment]
In principle the code that you share it looks nice to me @ginberg If you can reproduce the error or @jasgratton can I am happy to jump into a call and see what is going on

**Comment by ginberg** [comment]
@catalamarti ok, great if you can help with this. I will schedule a meeting for tomorrow, just let me know if the time doesn't work
