### ISSUE TITLE
update new route

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/DrugUtilisation#355]

**Comment by catalamarti** [comment]
[route to dose form OHDSI US_no other.csv](https://github.com/darwin-eu-dev/DrugUtilisation/files/13367027/route.to.dose.form.OHDSI.US_no.other.csv)

**Comment by tiozab** [comment]
[route to dose form OHDSI US_no other.csv](https://github.com/darwin-eu-dev/DrugUtilisation/files/13417381/route.to.dose.form.OHDSI.US_no.other.csv)
please use this version, I changed one row
