### ISSUE TITLE
update dose formulas

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/DrugUtilisation#356]
[validpattern_41.csv](https://github.com/darwin-eu-dev/DrugUtilisation/files/13367029/validpattern_41.csv)

NO USE OF ROUTE!

**Comment by tiozab** [comment]
[pattern_assessment_for_dose_final.xlsx](https://github.com/darwin-eu-dev/DrugUtilisation/files/13375351/pattern_assessment_for_dose_final.xlsx)

**Comment by tiozab** [comment]
the change from 31 to 41 patterns is the introduction of "unit" in amount and numerator. 
This "unit" concept 8510 shall be synonymous to "international unit" (8718), i.e. if a drug has sometimes unit and sometimes "international unit", the estimated dose should only output "international unit"

**Comment by tiozab** [comment]
[pattern_assessment_for_dose_final_corrected.xlsx](https://github.com/darwin-eu-dev/DrugUtilisation/files/13476735/pattern_assessment_for_dose_final_corrected.xlsx)
