### ISSUE TITLE
Typo in attrition

### ISSUE THREAD

**Issue by martaalcalde** [darwin-eu-dev/DrugUtilisation#358]
When computing the attrition after "generateDrugUtilisationCohortSet" instead of "washout" it appears "wahout" (reason_id = 4)

![image](https://github.com/darwin-eu-dev/DrugUtilisation/assets/91142894/b7c61eeb-b624-4b68-86fe-67bf29c290a7)

**Comment by catalamarti** [comment]
hi @martaalcalde thanks for reporting!
Do you think that you can open a PR that fixes it? :)
Otherwise I will assign @MimiYuchenGuo  hahahha

**Comment by martaalcalde** [comment]
Yes! I can try!!

**Comment by catalamarti** [comment]
#361
