### ISSUE TITLE
Inconsistent output and argument in "getDrugIngredientCodes"

### ISSUE THREAD

**Issue by martaalcalde** [darwin-eu-dev/DrugUtilisation#359]
getDrugIngredientCodes() it returns a list of 1 element when withConceptDetails = FALSE, but in arguments it is specified that it should return a vector

**Comment by edward-burn** [comment]
@martaalcalde I think this is an issue for CodelistGenerator, right? (i.e. for me?)

**Comment by edward-burn** [comment]
Fixed in CodelistGenerator https://github.com/darwin-eu/CodelistGenerator/pull/104/commits/ba489b268f3ad86cba94f1d61a6234a02d0375f2, thanks for reporting @martaalcalde !
