### ISSUE TITLE
computing dose when dose = 0

### ISSUE THREAD

**Issue by cheryltan** [darwin-eu-dev/DrugUtilisation#375]
Consider to change if daily dose = 0 to NA
Line 208-209 in dailyDose.R
dplyr::mutate(daily_dose = dplyr::if_else(
      .data$daily_dose <= 0, as.numeric(NA), .data$daily_dose

**Comment by tiozab** [comment]
can we dig a bit deeper here? It should not be 0 in the first place...

**Comment by tiozab** [comment]
@catalamarti I just double checked the code and there is no filtering on duration > 0 and quantity >0, so Cheryl made the correct suggestion!
