### ISSUE TITLE
benchmarkDrugUtilisation

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/DrugUtilisation#382]
hi @MimiYuchenGuo  could you please take a look o this function and create sth similar for drugutilisation?
https://github.com/darwin-eu-dev/IncidencePrevalence/blob/main/R/benchmarkIncidencePrevalence.R

**Comment by MimiYuchenGuo** [comment]
I already have one in the vignette, is this ok: https://github.com/darwin-eu-dev/DrugUtilisation/blob/9afde5b55b1a74fb1bbb1c26bc3169dd41dc1033/vignettes/benchmarkDusCapr.Rmd#L68
