### ISSUE TITLE
conceptSet input different from generateConceptCohortSet

### ISSUE THREAD

**Issue by tiozab** [darwin-eu-dev/DrugUtilisation#393]
I wanted to re-use my conceptSet in generateDrugUtilisationCohortSet that I made for the CDMConnector::generateConceptCohortSet, however it is not possible, I get the following error:
Error in `checkConceptSet()`:
! conceptSet must be a uniquely named list of integerish, no NA are allowed
Run `rlang::last_trace()` to see where the error occurred.

Am I missing something? Why is it not possible?

**Comment by catalamarti** [comment]
this should be solved with the new release

**Comment by tiozab** [comment]
Great!!
