### ISSUE TITLE
eraJoinMode reference

### ISSUE THREAD

**Issue by tiozab** [darwin-eu-dev/DrugUtilisation#395]
eraJoinMode
How two different continuous exposures are joined in an era. There are four options: "zero" the exposures are joined considering that the period between both continuous exposures the subject is treated with a daily dose of zero. The time between both exposures contributes to the total exposed time. "join" the exposures are joined considering that the period between both continuous exposures the subject is treated with a daily dose of zero. The time between both exposures does not contribute to the total exposed time. "previous" the exposures are joined considering that the period between both continuous exposures the subject is treated with the daily dose of the previous subexposure. The time between both exposures contributes to the total exposed time. "subsequent" the exposures are joined considering that the period between both continuous exposures the subject is treated with the daily dose of the subsequent subexposure. The time between both exposures contributes to the total exposed time.

Maybe there is a copy paste error? between zero and join, they sound very much alike?

**Comment by catalamarti** [comment]
#448
