### ISSUE TITLE
readme dose not uptodate

### ISSUE THREAD

**Issue by tiozab** [darwin-eu-dev/DrugUtilisation#408]
the readme about dose is not up to date any more, because we now estimate dose for all patterns

**Comment by tiozab** [comment]
feel free to just copy paste the pattern file from the manuscript for example. Supplementary table 2, maybe needs to be adapted (i.e. show less columns)
[Supplementary Material.docx](https://github.com/darwin-eu-dev/DrugUtilisation/files/14328384/Supplementary.Material.docx)

**Comment by tiozab** [comment]
@catalamarti feel free to assign me

**Comment by catalamarti** [comment]
hi @tiozab can you take a look and see if the new version looks good to you? #425
