### ISSUE TITLE
generateIngredientCohortSet to allow lists of grouped ingredients

### ISSUE THREAD

**Issue by daniellenewby** [darwin-eu-dev/DrugUtilisation#415]
At the moment i can generate a ingredient cohort based on the following code:

```
cdm <- generateIngredientCohortSet(
  cdm = cdm,
  name = "ache_inhibitors",
  ingredient = c("donepezil", "rivastigmine", "galantamine", "memantine"),
  durationRange = c(1, Inf),
  imputeDuration = "none",
  gapEra = 0,
  priorUseWashout = 0,
  priorObservation = 0,
  cohortDateRange = as.Date(c(starting_date, ending_date)),
  limit = "all",
  doseForm = NULL,
  ingredientRange = c(1, Inf)
)
```

However, this generates separate cohorts for each ingredient but in my case this is not what i want. I would like something like this:

```
cdm <- generateIngredientCohortSet(
  cdm = cdm,
  name = "ache_inhibitors",
  ingredient = list(ache_inhibitors = c("donepezil", "rivastigmine", "galantamine")),
                        c(memantine = "mematine")),
  durationRange = c(1, Inf),
  imputeDuration = "none",
  gapEra = 0,
  priorUseWashout = 0,
  priorObservation = 0,
  cohortDateRange = as.Date(c(starting_date, ending_date)),
  limit = "all",
  doseForm = NULL,
  ingredientRange = c(1, Inf)
)
```

The code above would generate two cohorts 1) containing all the ingredients in the list "donepezil", "rivastigmine", "galantamine" and the second cohort just with "mematine".  Also it would be good to have a option if a user wants to generate cohorts individually.

**Comment by catalamarti** [comment]
hi @MimiYuchenGuo  can you modify the code so Danielles reprex works? but the original one also works? 
thanks :)
