### ISSUE TITLE
no. of exposures in summarise drug use

### ISSUE THREAD

**Issue by tiozab** [darwin-eu-dev/DrugUtilisation#420]
I am a bit confused about what number_exposures means ? because there are 0s in the distribution. 
However, it seems "no exposure" is not taken into account when estimating duration  ? it just seems not consistent. Or I do not understand how someone can have no exposures of a certain drug. I would expect the distribution only take into account values >0.

![image](https://github.com/darwin-eu-dev/PatientProfiles/assets/94674809/102710fa-0f6e-4897-b906-23a739f53486)

**Comment by catalamarti** [comment]
if you have a cohort and some individuals are not exposed they are also taken into account in the summary.
You can subset your cohort to the individuals of interest (e.g. only the exposed ones) if your population of interest is different.
