### ISSUE TITLE
question on vignette / references for addDailyDose() and addDrugUse()

### ISSUE THREAD

**Issue by tiozab** [darwin-eu-dev/DrugUtilisation#428]
I was wondering about the input for addDailyDose() and addDRugUse().

the addDailyDose() wants a cdm table (because it needs drug_concept_id, quantity, drug_exposure_start_date and drug_exposure_end_date as columns).
the addDrugUse() wants a cohort (no further specification).

what if I want to add daily dose to a cohort (without summarising results)? 
it should be possible to use addDailydose() with a cohort because addDrugUse() works with a cohort and calls addDailyDose() within.

I would like to understand that :-)

**Comment by catalamarti** [comment]
in the new version there will be two functions to do that:
- addInitialDailyDose #487 
- addCumulativeDose #488
