### ISSUE TITLE
use inst

### ISSUE THREAD

**Issue by tiozab** [darwin-eu-dev/DrugUtilisation#459]
can those two file be put  from raw_data into inst folder so we can call it in DED package with system.file() function
  system.file("dose_form_final.csv",package = "DrugUtilisation")
  system.file("pattern_assessment_for_dose_final.csv",package = "DrugUtilisation")
@ginberg FYI
Thanks :-)

**Comment by tiozab** [comment]
update: we only need the file 
system.file("pattern_assessment_for_dose_final.csv",package = "DrugUtilisation")

**Comment by catalamarti** [comment]
We export `patternsWithFormula` is this not enough for what you need? @tiozab

**Comment by tiozab** [comment]
we depend on the DUS package when using the dailydosecoverage function which needs the pattern_assessment_for_dose_final.csv, therefore, if you put the file into your inst folder instead of raw_data folder we can call it directly from there in the DED package. 

We do it like this. If you can let me know how to do it differently with using the patternswithFormula file, I am all ear :-)

![image](https://github.com/darwin-eu-dev/DrugUtilisation/assets/94674809/3efa73df-fcb4-4ef0-ba68-360138b00198)

**Comment by catalamarti** [comment]
this is exported: `DrugUtilisation::patternsWithFormula` would that be enough?

**Comment by tiozab** [comment]
no, because I have the unit concept id only from patternTable (line 42) therefore knowing the concept name only as given in patternsWithFormula would be an additional unneeded joining step with cdm concept table, so we rather use the csv file pattern (line 52) and that is why we kindly ask you to put it in the inst folder instead of raw_data folder :-)

**Comment by tiozab** [comment]
Thank you!
