### ISSUE TITLE
dailyDoseCoverage() summarised result

### ISSUE THREAD

**Issue by tiozab** [darwin-eu-dev/DrugUtilisation#461]
just wondering whether the variable_name should be number_records for count_missing?
<img width="347" alt="image" src="https://github.com/darwin-eu-dev/DrugUtilisation/assets/94674809/2eef05aa-7331-40ea-a570-f969d21acf61">

and something other than daily_dose as well for percentage_missing. 
Just thinking because when I want to use the plotCharacteristics function and put daily_dose as variable name it will pick also count_missing and percentage_missing
from the vignette https://darwin-eu-dev.github.io/CohortCharacteristics/articles/a06_summarisePatientCharacteristics.html
chars |>
  filter(variable_name == "Age") |>
  plotCharacteristics(
    plotStyle = "boxplot",
    colour = "group_level",
    x = "group_level",
    facet = c("cdm_name")
  )

**Comment by tiozab** [comment]
Moreover, the function dailyDoseCoverage() outputs naturally NA in strata_level if one of the units is NA (that is possible).
However then, validateSummariseResults throws an error saying that no NA allowed in strata_level

**Comment by tiozab** [comment]
furthermore, it is unclear what the "count" means, in the mock I have 5 patients and 10 drug_exposure records, yet, the count totals to 324
![image](https://github.com/darwin-eu-dev/DrugUtilisation/assets/94674809/c672a425-1134-4242-8f64-85cf27ceead7)

**Comment by tiozab** [comment]
furthermore @ginberg has a problem with "result_id" when saving the summarised result in a csv and then reading it into shiny it says that ids are not unique (despite us only having result_id = 1)
any work around was not successful

**Comment by tiozab** [comment]
@catalamarti @MimiYuchenGuo for plotCharacteristics() min and max is required,  but in real data it screws up the plots due to outliers showing crazy max values, can min and max please be optional?

**Comment by tiozab** [comment]
I see that min and max is a requirement in ggplotly.... so annoying it screws up the scale of the plots

**Comment by catalamarti** [comment]
dailyDoseCoverage -> summariseDoseCoverage()
+ tableDoseCoverage()

**Comment by nmercadeb** [comment]
> Moreover, the function dailyDoseCoverage() outputs naturally NA in strata_level if one of the units is NA (that is possible). However then, validateSummariseResults throws an error saying that no NA allowed in strata_level

Here are some options to use for renaming missing values of "route", "unit", "pattern_id", "ingredient_name" (these would then go to either strata or group level columns):
- missing
- none
- empty
- unspecified
- blank
- N/A
- unkown

**Comment by catalamarti** [comment]
> > Moreover, the function dailyDoseCoverage() outputs naturally NA in strata_level if one of the units is NA (that is possible). However then, validateSummariseResults throws an error saying that no NA allowed in strata_level
> 
> Here are some options to use for renaming missing values of "route", "unit", "pattern_id", "ingredient_name" (these would then go to either strata or group level columns):
> 
> * missing
> * none
> * empty
> * unspecified
> * blank
> * N/A
> * unkown

I would go with `missing`

> > just wondering whether the variable_name should be number_records for count_missing? <img alt="image" width="347" src="https://private-user-images.githubusercontent.com/94674809/335190412-2eef05aa-7331-40ea-a570-f969d21acf61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MjU1MjMsIm5iZiI6MTcxOTkyNTIyMywicGF0aCI6Ii85NDY3NDgwOS8zMzUxOTA0MTItMmVlZjA1YWEtNzMzMS00MGVhLWE1NzAtZjk2OWQyMWFjZjYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDEzMDAyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhNDdiN2MzMDg5NmNiYmViMDZhM2QzNDBhNmQyMTg2NTFhODVjMTU2ZjdhOTAwZjcyNTJkZDU2NWY5ZTlhN2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.AhxfxUQBDrZxkHorh8no4VPoudseYTr9NjYRTIol6K8">
> > and something other than daily_dose as well for percentage_missing. Just thinking because when I want to use the plotCharacteristics function and put daily_dose as variable name it will pick also count_missing and percentage_missing from the vignette https://darwin-eu-dev.github.io/CohortCharacteristics/articles/a06_summarisePatientCharacteristics.html chars |> filter(variable_name == "Age") |> plotCharacteristics( plotStyle = "boxplot", colour = "group_level", x = "group_level", facet = c("cdm_name") )
> 
> How about "missing dose" in variable name, and count/percentage in estimate name?

I would keep same behavior
