### ISSUE TITLE
addIndication refactor

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/DrugUtilisation#469]
refactor addIndication:
- indicationGap -> indicationWindow
- indicationCohortId = NULL
- nameStyle = "indication_{window_name}"
the output will be the combination of current addIndication() |> indicationToStrata()

Then indicationToStrata should be deprecated

**Comment by ilovemane** [comment]
indicationGap -> indicationWindow() patientProfiles default(0,0).

indicationCohortId = NULL 

indicationDate = "cohort_start_date" changed to indexDate,

indicationToStrata remove as function and change the output of addIndication to indicationToStrata
