### ISSUE TITLE
summariseTreatmentDiscontinuation

### ISSUE THREAD

**Issue by catalamarti** [darwin-eu-dev/DrugUtilisation#473]
# treatment discontinuation -> Ed
summariseTreatmentDiscontinuation
[survival analysis indexDate = "cohort_start_date", eventDate = "cohort_end_date"]
- censorAtEndObservation = TRUE
- censorAtDeath = TRUE
- censorTable = NULL || censorDate = ""
- censorTableId = NULL

**Comment by rossdwilliams** [comment]
hi @catalamarti can you confirm if this is available in DU? we have a feasibility request that wants to look at discontinuation and switching

**Comment by catalamarti** [comment]
yes as explained here: https://darwin-eu-dev.github.io/DrugUtilisation/articles/treatment_discontinuation.html
@rossdwilliams
