### ISSUE TITLE
Stop reexporting generateConceptCohortSet?

### ISSUE THREAD

**Issue by edward-burn** [darwin-eu-dev/DrugUtilisation#477]
@catalamarti it is no longer necessary to reexport generateConceptCohortSet, right? https://github.com/darwin-eu-dev/DrugUtilisation/blob/88d104e19dbf399a6a1fd4dcd8247920683ef620/R/generateConceptCohortSet.R#L19

**Comment by catalamarti** [comment]
yes this has already been done in dev veerison #468
